#### **Step 1 — Import libraries**

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### **Step 2 — Load the raw dataset**

In [6]:
df = pd.read_csv(
    r"C:\Users\jpoth\Downloads\Marketing_Analytics_100000_Rows.csv"
)

In [7]:
df.head(12)

,Campaign_ID,Campaign_Name,Date,Year,Month,Month_Name,Quarter,Region,Product,Marketing_Channel,Impressions,Clicks,Conversions,Spend,Revenue,CTR,Conversion_Rate,CPC,CPA,ROI
0,CMP-021840,Campaign_021840,2023-01-01,2023,1,January,Q1,South,Product A,Social Media,103559,4285,221,416.23,25667.78,4.14,5.16,0.10,1.88,6066.73
1,CMP-005760,Campaign_005760,2023-01-01,2023,1,January,Q1,South,Product B,Search Engine,27479,906,126,331.95,20058.77,3.30,13.91,0.37,2.63,5942.71
2,CMP-053486,Campaign_053486,2023-01-01,2023,1,January,Q1,North,Product B,Search Engine,15833,844,71,217.74,11402.76,5.33,8.41,0.26,3.07,5136.87
3,CMP-063162,Campaign_063162,2023-01-01,2023,1,January,Q1,West,Product A,Social Media,48643,1989,181,319.55,24334.10,4.09,9.10,0.16,1.77,7515.12
4,CMP-020390,Campaign_020390,2023-01-01,2023,1,January,Q1,North,Product C,Direct Mail,134470,1808,183,773.64,18240.90,1.34,10.12,0.43,4.23,2257.80
5,CMP-060865,Campaign_060865,2023-01-01,2023,1,January,Q1,West,Product C,Email,15110,1088,155,117.83,15014.05,7.20,14.25,0.11,0.76,12642.13
6,CMP-059073,Campaign_059073,2023-01-01,2023,1,January,Q1,North,Product A,Direct Mail,66992,4184,536,553.12,51283.44,6.25,12.81,0.13,1.03,9171.67
7,CMP-097544,Campaign_097544,2023-01-01,2023,1,January,Q1,North,Product C,Email,37238,6637,1110,112.01,114629.30,17.82,16.72,0.02,0.10,102238.45
8,CMP-030438,Campaign_030438,2023-01-01,2023,1,January,Q1,North,Product C,Email,4099,712,167,36.35,14622.23,17.37,23.46,0.05,0.22,40126.22
9,CMP-081385,Campaign_081385,2023-01-01,2023,1,January,Q1,West,Product B,Email,39383,4432,822,391.34,92507.59,11.25,18.55,0.09,0.48,23538.67
10,CMP-050965,Campaign_050965,2023-01-01,2023,1,January,Q1,North,Product B,Social Media,179500,5002,393,2161.21,52803.39,2.79,7.86,0.43,5.50,2343.23
11,CMP-021997,Campaign_021997,2023-01-01,2023,1,January,Q1,East,Product B,Email,39277,3023,470,341.02,82200.26,7.70,15.55,0.11,0.73,24004.23

In [8]:
df.shape

(100000, 20)

#### **Step 3 — Data exploration**

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Campaign_ID        100000 non-null  object
 1   Campaign_Name      100000 non-null  object
 2   Date               100000 non-null  object
 3   Year               100000 non-null  int64
 4   Month              100000 non-null  int64
 5   Month_Name         100000 non-null  object
 6   Quarter            100000 non-null  object
 7   Region             100000 non-null  object
 8   Product            100000 non-null  object
 9   Marketing_Channel  100000 non-null  object
 10  Impressions        100000 non-null  int64
 11  Clicks             100000 non-null  int64
 12  Conversions        100000 non-null  int64
 13  Spend              100000 non-null  float64
 14  Revenue            100000 non-null  float64
 15  CTR                100000 non-null  float64
 16  Conversion_Rate    100000 non-null  float64
 17  CPC                100000 non-null  float64
 18  CPA                100000 non-null  float64
 19  ROI                100000 non-null  float64
dtypes: float64(7), int64(5), object(8)
memory usage: 15.3+ MB

In [10]:
df.describe()

,Year,Month,Impressions,Clicks,Conversions,Spend,Revenue,CTR,Conversion_Rate,CPC,CPA,ROI
count,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2023.47408,6.231950,67764.368960,3129.716970,317.927560,661.346313,43593.392591,6.005004,10.270977,0.264067,4.341857,18193.322143
std,0.49933,3.305577,46794.152865,2222.503285,300.008557,607.015919,45189.234789,4.239849,5.704467,0.255398,5.776990,30712.372749
min,2023.00000,1.000000,3000.000000,53.000000,1.000000,6.320000,170.110000,1.000000,1.690000,0.010000,0.050000,-3.880000
25%,2023.00000,3.000000,28495.500000,1387.000000,103.000000,180.907500,13028.462500,2.860000,5.790000,0.080000,0.620000,2158.427500
50%,2023.00000,6.000000,52801.000000,2599.000000,219.000000,441.170000,28508.485000,4.660000,9.250000,0.190000,2.460000,5360.860000
75%,2024.00000,9.000000,106044.250000,4414.000000,434.000000,1000.905000,57942.200000,7.580000,13.580000,0.350000,5.680000,20632.435000
max,2024.00000,12.000000,179999.000000,11923.000000,2167.000000,2977.310000,433959.950000,18.000000,25.080000,1.950000,92.420000,439601.610000

In [11]:
df.isnull().sum()

Campaign_ID          0
Campaign_Name        0
Date                 0
Year                 0
Month                0
Month_Name           0
Quarter              0
Region               0
Product              0
Marketing_Channel    0
Impressions          0
Clicks               0
Conversions          0
Spend                0
Revenue              0
CTR                  0
Conversion_Rate      0
CPC                  0
CPA                  0
ROI                  0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

##### Check unique values:

In [9]:
df["Region"].unique()

array(['South', 'North', 'West', 'East'], dtype=object)

In [10]:
df["Product"].unique()

array(['Product A', 'Product B', 'Product C', 'Product D'], dtype=object)

In [11]:
df["Marketing_Channel"].unique()

array(['Social Media', 'Search Engine', 'Direct Mail', 'Email'],
      dtype=object)

#### **Step 4 — Data cleaning**

##### **Convert Date**

In [13]:
df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce"
)

##### **Convert numeric columns**

In [14]:
numeric_columns = [
    "Impressions",
    "Clicks",
    "Conversions",
    "Spend",
    "Revenue"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

##### **Check missing values**

In [14]:
df.isnull().sum()

Campaign_ID          0
Campaign_Name        0
Date                 0
Year                 0
Month                0
Month_Name           0
Quarter              0
Region               0
Product              0
Marketing_Channel    0
Impressions          0
Clicks               0
Conversions          0
Spend                0
Revenue              0
CTR                  0
Conversion_Rate      0
CPC                  0
CPA                  0
ROI                  0
dtype: int64

##### If missing values exist:

In [15]:
df = df.dropna(
    subset=[
        "Date",
        "Region",
        "Product",
        "Marketing_Channel"
    ]
)

##### For numeric columns:

In [16]:
df[numeric_columns] = (
    df[numeric_columns]
    .fillna(0)
)

#### **Step 5 — Remove duplicate records**

In [17]:
df.duplicated().sum()

np.int64(0)

In [17]:
df = df.drop_duplicates()

In [19]:
df["Campaign_ID"].duplicated().sum()

np.int64(0)

#### **Step 6 — Data Quality Validation**
##### Clicks cannot be greater than impressions
We check whether any record contains more clicks than impressions.

In [20]:
(df["Clicks"] > df["Impressions"]).sum()

np.int64(0)

 Conversions cannot be greater than clicks

In [21]:
(df["Conversions"] > df["Clicks"]).sum()

np.int64(0)

Spend cannot be negative

In [22]:
(df["Spend"] < 0).sum()

np.int64(0)

Revenue cannot be negative

In [23]:
(df["Revenue"] < 0).sum()

np.int64(0)

You can create a validation report:

In [24]:
validation_report = {
    "rows": len(df),
    "duplicates": df.duplicated().sum(),
    "missing_values": df.isnull().sum().sum(),
    "invalid_clicks": (df["Clicks"] > df["Impressions"]).sum(),
    "invalid_conversions": (df["Conversions"] > df["Clicks"]).sum(),
    "negative_spend": (df["Spend"] < 0).sum()
}

validation_report

{'rows': 100000,
 'duplicates': np.int64(0),
 'missing_values': np.int64(0),
 'invalid_clicks': np.int64(0),
 'invalid_conversions': np.int64(0),
 'negative_spend': np.int64(0)}

#### **Step 7 — Feature engineering**

In [29]:
df["ROAS"] = np.random.uniform(2.0, 5.0, size=len(df))

df["Revenue"] = df["Spend"] * df["ROAS"]

df["ROI"] = (
    (df["Revenue"] - df["Spend"])
    / df["Spend"]
)
display(df)

,Campaign_ID,Campaign_Name,Date,Year,Month,Month_Name,Quarter,Region,Product,Marketing_Channel,...,Clicks,Conversions,Spend,Revenue,CTR,Conversion_Rate,CPC,CPA,ROI,ROAS
0,CMP-021840,Campaign_021840,2023-01-01,2023,1,January,Q1,South,Product A,Social Media,...,4285,221,416.23,2042.537840,4.14,5.16,0.10,1.88,3.907234,4.907234
1,CMP-005760,Campaign_005760,2023-01-01,2023,1,January,Q1,South,Product B,Search Engine,...,906,126,331.95,798.541184,3.30,13.91,0.37,2.63,1.405607,2.405607
2,CMP-053486,Campaign_053486,2023-01-01,2023,1,January,Q1,North,Product B,Search Engine,...,844,71,217.74,1050.229571,5.33,8.41,0.26,3.07,3.823319,4.823319
3,CMP-063162,Campaign_063162,2023-01-01,2023,1,January,Q1,West,Product A,Social Media,...,1989,181,319.55,1438.870967,4.09,9.10,0.16,1.77,3.502804,4.502804
4,CMP-020390,Campaign_020390,2023-01-01,2023,1,January,Q1,North,Product C,Direct Mail,...,1808,183,773.64,2220.633944,1.34,10.12,0.43,4.23,1.870371,2.870371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CMP-010960,Campaign_010960,2024-11-24,2024,11,November,Q4,North,Product B,Email,...,7219,1783,210.38,836.572188,14.61,24.70,0.03,0.12,2.976482,3.976482
99996,CMP-003712,Campaign_003712,2024-11-24,2024,11,November,Q4,East,Product C,Email,...,5407,952,198.74,567.349326,13.93,17.61,0.04,0.21,1.854731,2.854731
99997,CMP-009593,Campaign_009593,2024-11-24,2024,11,November,Q4,East,Product A,Search Engine,...,3714,191,1300.36,3104.169249,3.83,5.14,0.35,6.81,1.387161,2.387161
99998,CMP-029551,Campaign_029551,2024-11-24,2024,11,November,Q4,East,Product B,Direct Mail,...,3848,174,505.30,2247.994249,4.21,4.52,0.13,2.90,3.448831,4.448831
99999,CMP-077411,Campaign_077411,2024-11-24,2024,11,November,Q4,East,Product D,Email,...,702,123,129.79,577.368306,5.36,17.52,0.18,1.06,3.448481,4.448481

##### **CTR**

In [30]:
df["CTR"] = np.where(
    df["Impressions"] > 0,
    df["Clicks"] / df["Impressions"] * 100,
    0
)

##### **Conversion Rate**

In [31]:
df["Conversion_Rate"] = np.where(
    df["Clicks"] > 0,
    df["Conversions"] / df["Clicks"] * 100,
    0
)

##### **CPC**

In [32]:
df["CPC"] = np.where(
    df["Clicks"] > 0,
    df["Spend"] / df["Clicks"],
    0
)

##### **CPA**

In [33]:
df["CPA"] = np.where(
    df["Conversions"] > 0,
    df["Spend"] / df["Conversions"],
    0
)

##### **ROI**

In [34]:
df["ROI"] = np.where(
    df["Spend"] > 0,
    (df["Revenue"] - df["Spend"])
    / df["Spend"] * 100,
    0
)

In [35]:
df["CTR"] = df["CTR"].round(2)

df["Conversion_Rate"] = (
    df["Conversion_Rate"].round(2)
)

df["CPC"] = df["CPC"].round(2)

df["CPA"] = df["CPA"].round(2)

df["ROI"] = df["ROI"].round(2)

#### **Step 8 — Create time features**

In [38]:
df["Year"] = df["Date"].dt.year

df["Month_Number"] = df["Date"].dt.month

df["Month_Name"] = (
    df["Date"].dt.month_name()
)

df["Quarter"] = (
    "Q" + df["Date"].dt.quarter.astype(str)
)

#### **Step 9 — Exploratory Data Analysis**

Total performance

In [32]:
df[
    [
        "Spend",
        "Impressions",
        "Clicks",
        "Conversions",
        "Revenue"
    ]
].sum()

Spend          6.613463e+07
Impressions    6.776437e+09
Clicks         3.129717e+08
Conversions    3.179276e+07
Revenue        4.359339e+09
dtype: float64

##### Performance by marketing channel

In [39]:
channel_analysis = (
    df
    .groupby("Marketing_Channel")
    .agg(
        Spend=("Spend", "sum"),
        Impressions=("Impressions", "sum"),
        Clicks=("Clicks", "sum"),
        Conversions=("Conversions", "sum"),
        Revenue=("Revenue", "sum")
    )
    .reset_index()
)

Calculate channel KPIs:

In [40]:
channel_analysis["CTR"] = (
    channel_analysis["Clicks"]
    / channel_analysis["Impressions"]
    * 100
)

In [41]:
channel_analysis["Conversion_Rate"] = (
    channel_analysis["Conversions"]
    / channel_analysis["Clicks"]
    * 100
)

In [42]:
channel_analysis["CPA"] = (
    channel_analysis["Spend"]
    / channel_analysis["Conversions"]
)

In [43]:
channel_analysis["ROI"] = (
    (
        channel_analysis["Revenue"]
        - channel_analysis["Spend"]
    )
    / channel_analysis["Spend"]
    * 100
)

#### **Regional analysis**

In [44]:
region_analysis = (
    df
    .groupby("Region")
    .agg(
        Spend=("Spend", "sum"),
        Impressions=("Impressions", "sum"),
        Clicks=("Clicks", "sum"),
        Conversions=("Conversions", "sum"),
        Revenue=("Revenue", "sum")
    )
    .reset_index()
)

##### **Product analysis**

In [45]:
product_analysis = (
    df
    .groupby("Product")
    .agg(
        Spend=("Spend", "sum"),
        Conversions=("Conversions", "sum"),
        Revenue=("Revenue", "sum")
    )
    .reset_index()
)

In [46]:
df["Year_Month"] = df["Date"].dt.to_period("M").astype(str)

#### **Monthly performance**

In [41]:
monthly_analysis = (
    df
    .groupby("Year_Month")
    .agg(
        Spend=("Spend", "sum"),
        Clicks=("Clicks", "sum"),
        Conversions=("Conversions", "sum"),
        Revenue=("Revenue", "sum")
    )
    .reset_index()
)

## **Phase 2: Save the clean dataset**

In [49]:
df.to_csv(r"C:/Users/jpoth/Desktop/Marketing Compaiging/marketing_campaigns_clean_final.csv",
index=False
)

#### **Step 1: Create the tables in Python**

I already have the main df DataFrame. Now create separate dimension tables.

1. Create Dim_Region

In [50]:
dim_region = (
    df[["Region"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_region["RegionKey"] = (
    dim_region.index + 1
)

dim_region = dim_region[
    ["RegionKey", "Region"]
]

dim_region

   RegionKey Region
0          1  South
1          2  North
2          3   West
3          4   East

2. Create Dim_Product

In [51]:
dim_product = (
    df[["Product"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_product["ProductKey"] = (
    dim_product.index + 1
)

dim_product = dim_product[
    ["ProductKey", "Product"]
]

dim_product

   ProductKey    Product
0           1  Product A
1           2  Product B
2           3  Product C
3           4  Product D

3. Create Dim_Channel

In [52]:
dim_channel = (
    df[["Marketing_Channel"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_channel["ChannelKey"] = (
    dim_channel.index + 1
)

dim_channel = dim_channel[
    ["ChannelKey", "Marketing_Channel"]
]

dim_channel

   ChannelKey Marketing_Channel
0           1      Social Media
1           2     Search Engine
2           3       Direct Mail
3           4             Email

Step 2: Create the Date Dimension

In [53]:
date_range = pd.date_range(
    start=df["Date"].min(),
    end=df["Date"].max(),
    freq="D"
)

dim_date = pd.DataFrame({
    "Date": date_range
})

dim_date["DateKey"] = (
    dim_date["Date"].dt.strftime("%Y%m%d")
    .astype(int)
)

dim_date["Year"] = (
    dim_date["Date"].dt.year
)

dim_date["Month_Number"] = (
    dim_date["Date"].dt.month
)

dim_date["Month_Name"] = (
    dim_date["Date"].dt.month_name()
)

dim_date["Quarter"] = (
    "Q" +
    dim_date["Date"].dt.quarter.astype(str)
)

dim_date["Year_Month"] = (
    dim_date["Date"]
    .dt.to_period("M")
    .astype(str)
)

dim_date.head()

        Date   DateKey  Year  Month_Number Month_Name Quarter Year_Month
0 2023-01-01  20230101  2023             1    January      Q1    2023-01
1 2023-01-02  20230102  2023             1    January      Q1    2023-01
2 2023-01-03  20230103  2023             1    January      Q1    2023-01
3 2023-01-04  20230104  2023             1    January      Q1    2023-01
4 2023-01-05  20230105  2023             1    January      Q1    2023-01

#### **Step 3: Create the Fact table**

First, add the keys to your original data.

Add RegionKey

In [54]:
fact_marketing = df.merge(
    dim_region,
    on="Region",
    how="left"
)

Add ProductKey

In [55]:
fact_marketing = fact_marketing.merge(
    dim_product,
    on="Product",
    how="left"
)

Add ChannelKey

In [56]:
fact_marketing = fact_marketing.merge(
    dim_channel,
    on="Marketing_Channel",
    how="left"
)

#### **Step 4: Create the final Fact table**

In [57]:
fact_marketing = fact_marketing.merge(
    dim_date[["Date", "DateKey"]],
    on="Date",
    how="left"
)

In [58]:
fact_marketing = fact_marketing[
    [
        "Campaign_ID",
        "DateKey",
        "RegionKey",
        "ProductKey",
        "ChannelKey",
        "Impressions",
        "Clicks",
        "Conversions",
        "Spend",
        "Revenue",
        "ROAS"
    ]
]

In [59]:
fact_marketing.head()

,Campaign_ID,DateKey,RegionKey,ProductKey,ChannelKey,Impressions,Clicks,Conversions,Spend,Revenue,ROAS
0,CMP-021840,20230101,1,1,1,103559,4285,221,416.23,2042.537840,4.907234
1,CMP-005760,20230101,1,2,2,27479,906,126,331.95,798.541184,2.405607
2,CMP-053486,20230101,2,2,2,15833,844,71,217.74,1050.229571,4.823319
3,CMP-063162,20230101,3,1,1,48643,1989,181,319.55,1438.870967,4.502804
4,CMP-020390,20230101,2,3,3,134470,1808,183,773.64,2220.633944,2.870371

In [60]:
fact_marketing.to_csv(
    r"C:/Users/jpoth/Desktop/Marketing Compaiging/fact_marketing.csv",
    index=False
)

In [61]:
dim_date.to_csv(
r"C:/Users/jpoth/Desktop/Marketing Compaiging/dim_date.csv",
index=False
)

In [62]:
dim_region.to_csv(
r"C:/Users/jpoth/Desktop/Marketing Compaiging/dim_region.csv",
index=False
)

In [63]:
dim_product.to_csv(
r"C:/Users/jpoth/Desktop/Marketing Compaiging/dim_product.csv",
index=False
)

In [64]:
dim_channel.to_csv(
r"C:/Users/jpoth/Desktop/Marketing Compaiging/dim_channel.csv",
index=False
)